---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: praveen-ns
  labels:
    type: appserver
    author: Praveen
spec:
  replicas: 10
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...

