---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: proxy
    author: Praveen
spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: ngnix-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
...
