---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: proxy
    author: Praveen
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: slave1
              operator: In
              values:
                - praveen
...                  
