---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test-ns
  labels:
    author: praveen
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
        - containerPort: 9090
          hostPort: 9090
...
