---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  namespace: test-ns
  labels:
    type: mydb
    author: praveen
spec:
  containers: 
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: praveen
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_DB
          value: mydb
...
