---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    type: db
    author: Praveen
spec:
  containers:
    - name: mydb
      image: redis
      volumeMounts:
        - name: myvolume
          mountPath: /data/redis
  volumes:
    - name: myvolume
      emptyDir: {}
...
