---
apiVersion: v1
kind: Service
metadata:
  name: newservice
  labels:
    author: Praveen
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    author: Praveen
    type: proxy
...
