---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: test-ns
  labels:
    type: ci-cd
    author: praveen
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
        - containerPort: 9090
          hostPort: 9090

...
