---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deplyment
  labels:
    type: appserver
    author: Praveen
spec:
  replicas: 6
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
...
