---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-nginx-deployment
  labels:
    type: proxy
    author: Praveen
spec:
  replicas: 1
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: ngnix-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx:1.27
...
